[package]
name = "semver_sort"
version = "0.1.0"
description = "Sorts semver strings or numbers"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
